"""Export a reconstructed PGN tree to the JSON shape the local viewer consumes.

Each node: {san, uci, fen, children:[...]}. The viewer renders the FEN directly
(no JS chess engine needed) and walks children for the variation tree. This keeps
the desktop viewer fully static/portable while staying byte-for-byte consistent
with the Python rules engine.

Run: python engine/tree_json.py   ->  writes viewer/samples.js
"""

import json
import os
import sys

import chess
import chess.pgn

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from engine.fen_tree import build_tree


def serialize(node: chess.pgn.GameNode) -> list[dict]:
    board = node.board()
    out = []
    for child in node.variations:
        out.append(
            {
                "san": board.san(child.move),
                "uci": child.move.uci(),
                "fen": child.board().fen(),
                "children": serialize(child),
            }
        )
    return out


def game_to_root(game: chess.pgn.Game) -> dict:
    return {"start_fen": game.board().fen(), "children": serialize(game)}


def line_placements(sans: list[str]) -> list[str]:
    board = chess.Board()
    out = []
    for san in sans:
        board.push_san(san)
        out.append(board.board_fen())
    return out


def benko_sample() -> dict:
    mainline = ["d4", "Nf6", "c4", "c5", "d5", "b5", "cxb5", "a6", "bxa6"]
    placements = line_placements(mainline)
    placements.append(placements[-1])                       # duplicate frame (noise)
    placements.append(placements[5])                        # takeback to after 3...b5
    placements.append(line_placements(mainline[:6] + ["Nf3"])[-1])  # 4.Nf3 variation
    game, _ = build_tree(placements)
    return {
        "id": "graif-benko",
        "name": "Graif-Benko Gambit",
        "source": "The Gambit Man — FM William Graif",
        "orientation": "black",
        "root": game_to_root(game),
    }


def italian_sample() -> dict:
    mainline = ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "c3", "Nf6"]
    placements = line_placements(mainline)
    placements.append(placements[3])                        # takeback to after 2...Nc6
    placements.append(line_placements(["e4", "e5", "Nf3", "Nc6", "Bb5"])[-1])  # 3.Bb5 (Ruy) variation
    game, _ = build_tree(placements)
    return {
        "id": "italian-demo",
        "name": "Italiensk / Ruy (eksempel)",
        "source": "Eksempeldata",
        "orientation": "white",
        "root": game_to_root(game),
    }


def main() -> int:
    samples = [benko_sample(), italian_sample()]
    out_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "viewer"))
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "samples.js")
    payload = json.dumps(samples, ensure_ascii=False, indent=2)
    with open(out_path, "w", encoding="utf-8") as handle:
        handle.write("// Auto-generated by engine/tree_json.py — seed data for the viewer.\n")
        handle.write("window.RINDEN_SAMPLES = " + payload + ";\n")
    print("wrote:", out_path)
    print("samples:", ", ".join(s["name"] for s in samples))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
