// Auto-generated by engine/tree_json.py — seed data for the viewer.
window.RINDEN_SAMPLES = [
  {
    "id": "graif-benko",
    "name": "Graif-Benko Gambit",
    "source": "The Gambit Man — FM William Graif",
    "orientation": "black",
    "root": {
      "start_fen": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
      "children": [
        {
          "san": "d4",
          "uci": "d2d4",
          "fen": "rnbqkbnr/pppppppp/8/8/3P4/8/PPP1PPPP/RNBQKBNR b KQkq - 0 1",
          "children": [
            {
              "san": "Nf6",
              "uci": "g8f6",
              "fen": "rnbqkb1r/pppppppp/5n2/8/3P4/8/PPP1PPPP/RNBQKBNR w KQkq - 1 2",
              "children": [
                {
                  "san": "c4",
                  "uci": "c2c4",
                  "fen": "rnbqkb1r/pppppppp/5n2/8/2PP4/8/PP2PPPP/RNBQKBNR b KQkq - 0 2",
                  "children": [
                    {
                      "san": "c5",
                      "uci": "c7c5",
                      "fen": "rnbqkb1r/pp1ppppp/5n2/2p5/2PP4/8/PP2PPPP/RNBQKBNR w KQkq - 0 3",
                      "children": [
                        {
                          "san": "d5",
                          "uci": "d4d5",
                          "fen": "rnbqkb1r/pp1ppppp/5n2/2pP4/2P5/8/PP2PPPP/RNBQKBNR b KQkq - 0 3",
                          "children": [
                            {
                              "san": "b5",
                              "uci": "b7b5",
                              "fen": "rnbqkb1r/p2ppppp/5n2/1ppP4/2P5/8/PP2PPPP/RNBQKBNR w KQkq - 0 4",
                              "children": [
                                {
                                  "san": "cxb5",
                                  "uci": "c4b5",
                                  "fen": "rnbqkb1r/p2ppppp/5n2/1PpP4/8/8/PP2PPPP/RNBQKBNR b KQkq - 0 4",
                                  "children": [
                                    {
                                      "san": "a6",
                                      "uci": "a7a6",
                                      "fen": "rnbqkb1r/3ppppp/p4n2/1PpP4/8/8/PP2PPPP/RNBQKBNR w KQkq - 0 5",
                                      "children": [
                                        {
                                          "san": "bxa6",
                                          "uci": "b5a6",
                                          "fen": "rnbqkb1r/3ppppp/P4n2/2pP4/8/8/PP2PPPP/RNBQKBNR b KQkq - 0 5",
                                          "children": []
                                        }
                                      ]
                                    }
                                  ]
                                },
                                {
                                  "san": "Nf3",
                                  "uci": "g1f3",
                                  "fen": "rnbqkb1r/p2ppppp/5n2/1ppP4/2P5/5N2/PP2PPPP/RNBQKB1R b KQkq - 1 4",
                                  "children": []
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    }
  },
  {
    "id": "italian-demo",
    "name": "Italiensk / Ruy (eksempel)",
    "source": "Eksempeldata",
    "orientation": "white",
    "root": {
      "start_fen": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
      "children": [
        {
          "san": "e4",
          "uci": "e2e4",
          "fen": "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1",
          "children": [
            {
              "san": "e5",
              "uci": "e7e5",
              "fen": "rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2",
              "children": [
                {
                  "san": "Nf3",
                  "uci": "g1f3",
                  "fen": "rnbqkbnr/pppp1ppp/8/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R b KQkq - 1 2",
                  "children": [
                    {
                      "san": "Nc6",
                      "uci": "b8c6",
                      "fen": "r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3",
                      "children": [
                        {
                          "san": "Bc4",
                          "uci": "f1c4",
                          "fen": "r1bqkbnr/pppp1ppp/2n5/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 3",
                          "children": [
                            {
                              "san": "Bc5",
                              "uci": "f8c5",
                              "fen": "r1bqk1nr/pppp1ppp/2n5/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4",
                              "children": [
                                {
                                  "san": "c3",
                                  "uci": "c2c3",
                                  "fen": "r1bqk1nr/pppp1ppp/2n5/2b1p3/2B1P3/2P2N2/PP1P1PPP/RNBQK2R b KQkq - 0 4",
                                  "children": [
                                    {
                                      "san": "Nf6",
                                      "uci": "g8f6",
                                      "fen": "r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/2P2N2/PP1P1PPP/RNBQK2R w KQkq - 1 5",
                                      "children": []
                                    }
                                  ]
                                }
                              ]
                            }
                          ]
                        },
                        {
                          "san": "Bb5",
                          "uci": "f1b5",
                          "fen": "r1bqkbnr/pppp1ppp/2n5/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 3",
                          "children": []
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    }
  }
];
